### ISSUE TITLE
isExtendedError cannot handle batch responses

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client-core#34]
isExtendedError works as it should if the action is executed on single item but it return false if a batch action returns with an error, because in this case the error is a level lower in the response

**Comment by gallayl** [comment]
isExtendedError() is a type guard for Error objects, the problem is that batch responses doesn't throw errors.
We should refactor the MessageBar (component and store layer) and extract the message type evaluation from the component itself. We can also improve batching of the messages. (se attached pr)
